export const products = [
  {
    id: 'p1',
    name: 'Wireless Headphones',
    category: 'Electronics',
    price: 79.99,
    stock: 12,
    image: 'https://picsum.photos/seed/headphones/400/300',
    description: 'Over-ear wireless headphones with active noise cancellation and 30-hour battery life.',
  },
  {
    id: 'p2',
    name: 'Smart Watch',
    category: 'Electronics',
    price: 149.99,
    stock: 8,
    image: 'https://picsum.photos/seed/smartwatch/400/300',
    description: 'Track your fitness, heart rate, and notifications right from your wrist.',
  },
  {
    id: 'p3',
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    price: 39.99,
    stock: 20,
    image: 'https://picsum.photos/seed/speaker/400/300',
    description: 'Portable waterproof speaker with rich bass and 12-hour playtime.',
  },
  {
    id: 'p4',
    name: 'Mechanical Keyboard',
    category: 'Electronics',
    price: 89.99,
    stock: 15,
    image: 'https://picsum.photos/seed/keyboard/400/300',
    description: 'RGB backlit mechanical keyboard with hot-swappable switches.',
  },
  {
    id: 'p5',
    name: "Men's Running Shoes",
    category: 'Clothing',
    price: 64.99,
    stock: 25,
    image: 'https://picsum.photos/seed/runningshoes/400/300',
    description: 'Lightweight breathable running shoes with cushioned soles.',
  },
  {
    id: 'p6',
    name: 'Denim Jacket',
    category: 'Clothing',
    price: 54.99,
    stock: 10,
    image: 'https://picsum.photos/seed/denimjacket/400/300',
    description: 'Classic fit denim jacket, perfect for layering in any season.',
  },
  {
    id: 'p7',
    name: 'Cotton T-Shirt (3-Pack)',
    category: 'Clothing',
    price: 24.99,
    stock: 40,
    image: 'https://picsum.photos/seed/tshirt/400/300',
    description: 'Soft, breathable 100% cotton t-shirts in a pack of three.',
  },
  {
    id: 'p8',
    name: 'Non-Stick Cookware Set',
    category: 'Home & Kitchen',
    price: 119.99,
    stock: 6,
    image: 'https://picsum.photos/seed/cookware/400/300',
    description: '10-piece non-stick cookware set, dishwasher safe.',
  },
  {
    id: 'p9',
    name: 'Espresso Machine',
    category: 'Home & Kitchen',
    price: 199.99,
    stock: 5,
    image: 'https://picsum.photos/seed/espresso/400/300',
    description: 'Compact espresso machine with built-in milk frother.',
  },
  {
    id: 'p10',
    name: 'Memory Foam Pillow',
    category: 'Home & Kitchen',
    price: 29.99,
    stock: 30,
    image: 'https://picsum.photos/seed/pillow/400/300',
    description: 'Contour memory foam pillow for better neck support.',
  },
  {
    id: 'p11',
    name: 'The Pragmatic Programmer',
    category: 'Books',
    price: 34.99,
    stock: 18,
    image: 'https://picsum.photos/seed/book1/400/300',
    description: 'A classic guide to becoming a better, more pragmatic software developer.',
  },
  {
    id: 'p12',
    name: 'Atomic Habits',
    category: 'Books',
    price: 16.99,
    stock: 22,
    image: 'https://picsum.photos/seed/book2/400/300',
    description: 'An easy and proven way to build good habits and break bad ones.',
  },
  {
    id: 'p13',
    name: 'Yoga Mat',
    category: 'Sports',
    price: 22.99,
    stock: 35,
    image: 'https://picsum.photos/seed/yogamat/400/300',
    description: 'Extra thick non-slip yoga mat with carrying strap.',
  },
  {
    id: 'p14',
    name: 'Adjustable Dumbbell Set',
    category: 'Sports',
    price: 129.99,
    stock: 7,
    image: 'https://picsum.photos/seed/dumbbell/400/300',
    description: 'Space-saving adjustable dumbbells, 5-25 lbs per hand.',
  },
  {
    id: 'p15',
    name: 'Insulated Water Bottle',
    category: 'Sports',
    price: 19.99,
    stock: 50,
    image: 'https://picsum.photos/seed/bottle/400/300',
    description: 'Keeps drinks cold for 24 hours or hot for 12 hours.',
  },
  {
    id: 'p16',
    name: 'Backpack',
    category: 'Clothing',
    price: 44.99,
    stock: 16,
    image: 'https://picsum.photos/seed/backpack/400/300',
    description: 'Durable everyday backpack with laptop compartment.',
  },
];
