const products = [
  {
    id: 'p1',
    name: 'Wireless Headphones',
    price: 59.99,
    emoji: '🎧',
    category: 'Electronics',
    description: 'Over-ear Bluetooth headphones with noise cancellation.',
    stock: 8,
  },
  {
    id: 'p2',
    name: 'Mechanical Keyboard',
    price: 89.5,
    emoji: '⌨️',
    category: 'Electronics',
    description: 'Tactile mechanical keyboard with RGB backlighting.',
    stock: 5,
  },
  {
    id: 'p3',
    name: 'Ceramic Coffee Mug',
    price: 14.0,
    emoji: '☕',
    category: 'Home',
    description: '12oz ceramic mug, dishwasher and microwave safe.',
    stock: 20,
  },
  {
    id: 'p4',
    name: 'Running Shoes',
    price: 74.99,
    emoji: '👟',
    category: 'Apparel',
    description: 'Lightweight running shoes with breathable mesh.',
    stock: 6,
  },
  {
    id: 'p5',
    name: 'Yoga Mat',
    price: 24.99,
    emoji: '🧘',
    category: 'Fitness',
    description: 'Non-slip yoga mat, 6mm thick.',
    stock: 12,
  },
  {
    id: 'p6',
    name: 'Backpack',
    price: 45.0,
    emoji: '🎒',
    category: 'Apparel',
    description: 'Water-resistant backpack with laptop sleeve.',
    stock: 10,
  },
  {
    id: 'p7',
    name: 'Desk Lamp',
    price: 32.5,
    emoji: '💡',
    category: 'Home',
    description: 'Adjustable LED desk lamp with 3 brightness levels.',
    stock: 15,
  },
  {
    id: 'p8',
    name: 'Water Bottle',
    price: 18.0,
    emoji: '🚰',
    category: 'Fitness',
    description: 'Insulated stainless steel water bottle, 750ml.',
    stock: 25,
  },
  {
    id: 'p9',
    name: 'Sunglasses',
    price: 39.99,
    emoji: '🕶️',
    category: 'Apparel',
    description: 'Polarized UV-protection sunglasses.',
    stock: 0,
  },
]

export default products
